[config]
default_to_workspace = false


[tasks.unit-tests]
script = [
    "cargo test -p vertigo --all-features"
]

# NOTE: WebDriver on localhost:9515 needs to be running
[tasks.automated-tests]
script = [
    "cargo test --package fantoccini-tests -- --test-threads=1 --ignored"
]

[tasks.all-tests]
dependencies = [ "unit-tests", "automated-tests" ]

# Run clippy for wasm32 target

[tasks.clippy-wasm32]
command = "cargo"
args = [
    "clippy",
    "--all-features",
    "--target", "wasm32-unknown-unknown",
    "-p", "vertigo",
    "-p", "vertigo-macro",
    "-p", "vertigo-demo",
    "-p", "vertigo-example-counter",
    "-p", "vertigo-example-router",
    "-p", "vertigo-example-trafficlights"
]


# Demo tasks

[tasks.demo-serve-api]
script = [
    "cargo run --bin vertigo-demo-server"
]

[tasks.demo-watch]
script = [
    'cargo run --bin vertigo -- watch vertigo-demo --dest-dir=demo_build --env ws_chat=ws://127.0.0.1:3333/ws'
]

[tasks.demo-start]
script = [
    "cargo run --bin vertigo -- build vertigo-demo --dest-dir=demo_build",
    "cargo run --bin vertigo -- serve --dest-dir=demo_build --env ws_chat=ws://127.0.0.1:3333/ws"
]

[tasks.demo]
run_task = { name = ["demo-serve-api", "demo-watch"], parallel = true }

# Examples tasks
[tasks.examples-counter]
script = [
    'cargo run --bin vertigo -- watch vertigo-example-counter --dest-dir=examples/build/counter',
]

[tasks.examples-router]
script = [
    'cargo run --bin vertigo -- watch vertigo-example-router --dest-dir=examples/build/router',
]

[tasks.examples-trafficlights]
script = [
    'cargo run --bin vertigo -- watch vertigo-example-trafficlights --dest-dir=examples/build/trafficlights',
]

# JavaScript dev builds

[tasks.internal-run-ts]
private = true
command = "npx"
args = [ "-p", "typescript", "tsc",
    "--strict",
    "--noUnusedLocals", "--noUnusedParameters", "--noUncheckedIndexedAccess",
    "--noEmitOnError",
    "--lib", "es6,dom,esnext",
    "--target", "esnext",
    "--module", "es6",
    "--outDir", "crates/vertigo/src/driver_module/src_js_build",
    "crates/vertigo/src/driver_module/src_js/index.ts",
]

[tasks.build-js]
dependencies = [ "internal-run-ts" ]
script = [
    "npx rollup crates/vertigo/src/driver_module/src_js_build/index.js --file crates/vertigo/src/driver_module/wasm_run.js",
    "rm -rf crates/vertigo/src/driver_module/src_js_build",
]

[tasks.lint]
script = "cargo run --bin lint-project"
