[package]
name = "vertigo-testing"
description = "Harness for end-to-end browser tests of vertigo apps"
documentation = "https://docs.rs/vertigo-testing/"
categories = ["development-tools::testing", "wasm", "web-programming"]
keywords = ["vertigo", "e2e", "testing", "webdriver", "browser"]
version.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
actix-web = "4.15"
anyhow = "1.0"
libtest-mimic = "0.8"
reqwest = { version = "0.13", default-features = false, features = ["json"] }
serde_json = "1.0"
thirtyfour = "0.37"
tokio = { version = "1", features = ["rt-multi-thread", "process", "time", "sync"] }
vertigo-cli = { workspace = true }

[lints]
workspace = true
